[upstream]
purl = "pkg:github/qweered/nix-output-monitor?branch=main"

[locks]
hackage = "."

[[source]]
key = "default"
url = "https://github.com/qweered/nix-output-monitor/archive/{rev}.tar.gz"
hash = "sha256-vaOAXpaEtAuVE76IaliwKT8zpNttzN3ja3wvRozKmnA="

[pin]
version = "2.2.0-unstable-2026-09-30"
date = "2026-09-30"
rev = "0014da1ab4277b86ea9c58cc8f56fe6a20fe9f21"
sys = ["zlib"]
