[upstream]
purl = "pkg:github/llvm/llvm-project"
allow = ">=23"

[[source]]
key = "default"
url = "https://github.com/llvm/llvm-project/releases/download/{tag}/llvm-project-{version}.src.tar.xz"
hash = "sha256-iAcWcsfrEk2V9siWaMcUBzSBLcCh7oubhorrKmh/EBg="

[pin]
version = "23.1.1"
tag = "llvmorg-23.1.1"
date = "2025-12-16"
